# Generated by Django 4.1.3 on 2023-02-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authors',
            new_name='author',
        ),
    ]
