# Generated by Django 4.1.3 on 2023-02-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='object_type',
            new_name='object_id',
        ),
    ]
