# Generated by Django 4.1.3 on 2023-02-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_rename_object_type_tag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
